### ISSUE TITLE
Project kan bara ladda fram 4 jämna projekt

### ISSUE THREAD

**Issue by pownas** [matildawee/Projekt-IK201G#32]
Blir det t.ex. inte delbart med 4 , så laddas inte den sista sidan fram alls. 
T.ex. vid 11st så kommer bara 4 - 4 - null upp, den 3e sidan visas inte alls.

**Comment by pownas** [comment]
Löste vi denna igår? 
Går det att vissa t.ex 9-12 projekt på sidan nu?

@Bendrik och @matildawee

**Comment by Bendrik** [comment]
Japp alla projekt visas

**Comment by pownas** [comment]
Detta löstes av Oskar och Matilda i torsdags.
